apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-gateway
  template:
    metadata:
      labels:
        app: auth-gateway
    spec:
      containers:
        - name: auth-gateway
          image: datatrust360/auth-gateway:0.1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-gateway
spec:
  selector:
    app: auth-gateway
  ports:
    - port: 8080
      targetPort: 8080
