apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest-grpc
  template:
    metadata:
      labels:
        app: ingest-grpc
    spec:
      containers:
        - name: ingest-grpc
          image: datatrust360/ingest-grpc:0.1.0
          ports:
            - containerPort: 8082
            - containerPort: 9090
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: ingest-grpc
spec:
  selector:
    app: ingest-grpc
  ports:
    - port: 8082
      targetPort: 8082
    - port: 9090
      targetPort: 9090
