spring:
  application:
    name: processing-worker
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
